- name: Install Postgress
  hosts: localhost
  connection: local
  tasks:
  - name: Install postgres packages
    sudo: yes
    yum: name={{ item }} state=latest
    with_items:
      - postgresql-server
      - python-psycopg2

