- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ansibleResourceGroup
      name: AnsiblePushedVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqWtx12cGNaBT0YmEO99vTRW7TvdwyGpvEzjaNXRxnwWrc6xLNgElypOPeyvcAMXQ0T3vgFXFpHuMc+T+dDj0XavSzqDfoJ0GtHbRRO6GdEih0P8e9pLlhOZNgGgPk7arFI9n6rQgcLPrA5vZevKUY+Nr5dvf5PyckloKCWPfITWo55Y64xXIQ+gAx84B/Js7zlVF3sWld5ImPXoQ8lAcWyBlpzY710DJcBcWj2Uqw0DaPftZtLWyvRJNLLCoE7fwzYW3q6dPbr7NeP9r1xkji38QaOw89fV8zOQsxzT2W3aqLmLUQ0cIiZH80xTxofrb3dTtm5dYbc8GM4hnEHeH3 "
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest