- name: Install Postgress
  hosts: test[all]
  tasks:
  - name: Install postgres packages
    sudo: yes
    yum: name={{ item }} state=latest
    with_items:
      - postgresql-server
      - python-psycopg2

